name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "💥 Breaking Changes"
    labels:
      - breaking-change
  - title: "💡 New Features"
    labels:
      - feature
      - enhancement
  - title: "🐞 Bug Fixes"
    labels:
      - bug
      - fix
      - bugfix
  - title: "📝 Documentation"
    labels:
      - documentation
  - title: "⚙️ Technical Debt"
    labels:
      - refactor
  - title: "🧰 Maintenance"
    label: chore
  - title: "⬆️ Dependencies"
    collapse-after: 8
    labels:
      - dependencies

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
no-changes-template: "No significant changes"

template: |
  ## 🚀 Release

  ### What's Changed
  $CHANGES

  **Contributors:** $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

# See https://github.com/release-drafter/release-drafter#autolabeler
# This is more like a reference, since auto-labeling PRs seems to require too many privileges
autolabeler:
  - label: 'dependencies'
    files:
      - 'gradle-wrapper.properties'
    title:
      - '/^fix\(deps\)/i'
      - '/^chore:\s*bump/i'
  - label: 'chore'
    files:
      - '*gradle*'
      - '.github/**'
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - '/^chore/i'
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/^feat/i'
