name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# GitHub Actions does not support Docker, PostgreSQL server on Windows, macOS :(

jobs:
  ubuntu-latest:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        fetch-depth: 50
    - name: 'Set up Java'
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        java-version: |
          17
          21
        distribution: 'zulu'
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      name: Cache ./gradle/caches/
      with:
        path: |
          ~/.gradle/caches/
        key: gradle-${{ runner.os }}-caches-${{ hashFiles('build.properties', '**/*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
    - name: Test with Java 17
      uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
      with:
        gradle-version: wrapper
        arguments: --no-parallel --no-daemon -PtestJdk=17 build
    - name: Test with Java 21
      uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
      with:
        gradle-version: wrapper
        arguments: --no-parallel --no-daemon -PtestJdk=21 build
